name: SpikeGPU
highlighter: pygments

navigation: 
  - 
    title: Home
    url: /
  -
    title: Publications
    url: /publications/
  -
    title: Download
    url: /download/
  -
    title: Documentation
    url: /docs/
  -
    title: Nightly
    url: /nightly_build/
  -
    title: Contact
    url: /contact/
