name: SpikeGPU
markdown: redcarpet
pygments: true

navigation: 
  - 
    title: Home
    url: /
  -
    title: Publications
    url: /publications/
  -
    title: Download
    url: /download/
  -
    title: Documentation
    url: /docs/
  -
    title: Contact
    url: /contact/
